import { Sparkles, User } from "lucide-react";

const MessageBubble = ({ message }) => {
  const isUser = message.role === "user";
  const Icon = isUser ? User : Sparkles;
  const bubbleClasses = isUser
    ? "ml-auto bg-sky-500/15 border border-sky-300/20 text-sky-50 shadow-glow"
    : "mr-auto bg-white/10 border border-white/10 text-white shadow-lg";

  const metaParts = [];
  if (message.meta?.provider) metaParts.push(`Provider: ${message.meta.provider}`);
  if (message.meta?.model) metaParts.push(`Model: ${message.meta.model}`);
  if (message.meta?.usage) {
    const usageParts = [];
    if (message.meta.usage.prompt_tokens != null) {
      usageParts.push(`prompt ${message.meta.usage.prompt_tokens}`);
    }
    if (message.meta.usage.completion_tokens != null) {
      usageParts.push(`completion ${message.meta.usage.completion_tokens}`);
    }
    if (message.meta.usage.total_tokens != null) {
      usageParts.push(`total ${message.meta.usage.total_tokens}`);
    }
    if (usageParts.length) {
      metaParts.push(`Tokens: ${usageParts.join(", ")}`);
    }
  }
  if (message.meta?.latencyMs !== undefined && message.meta.latencyMs !== null) {
    metaParts.push(`Latency: ${message.meta.latencyMs}ms`);
  }
  if (message.meta?.mode) metaParts.push(`Mode: ${message.meta.mode}`);
  if (message.meta?.backendMode) {
    const backendLabels = {
      stub: "stub model",
      ollama: "local model",
      remote: "remote model",
    };
    const label = backendLabels[message.meta.backendMode] || message.meta.backendMode;
    metaParts.push(`Answer generated by ${label}`);
    if (message.meta?.fallbackReason) {
      metaParts.push(`Fallback: ${message.meta.fallbackReason}`);
    }
  }
  const metaText = metaParts.join(" | ");

  return (
    <div className={`max-w-[92%] rounded-2xl p-3 mb-3 backdrop-blur ${bubbleClasses}`}>
      <div className="flex items-center gap-2 text-xs uppercase tracking-wide text-slate-200/80">
        <Icon className="h-4 w-4" />
        {isUser ? "You" : "Assistant"}
      </div>
      <p className="mt-1 text-sm leading-relaxed">{message.content}</p>
      {metaText && <p className="mt-2 text-[11px] text-slate-200/80">{metaText}</p>}
    </div>
  );
};

export default MessageBubble;
