import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { vi } from "vitest";
import App from "./App";

const TEST_IMAGE = "data:image/png;base64,ZmFrZQ==";

vi.mock("./components/ImageUploader", () => ({
  default: ({ onFileSelected }) => (
    <button type="button" onClick={() => onFileSelected(TEST_IMAGE)}>
      UploaderMock
    </button>
  ),
}));

vi.mock("./api/client", () => ({
  askQuestion: vi.fn(),
}));

import { askQuestion } from "./api/client";

describe("App", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("sends question, mode, and image to the worker", async () => {
    askQuestion.mockResolvedValue({
      ok: true,
      data: {
        answer: "ok",
      },
    });

    render(<App />);
    fireEvent.click(screen.getByRole("button", { name: /uploadermock/i }));
    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "What is here?" } });

    const button = screen.getByRole("button", { name: /send question/i });
    expect(button).not.toBeDisabled();
    fireEvent.click(button);

    await waitFor(() => {
      expect(askQuestion).toHaveBeenCalledWith({
        question: "What is here?",
        mode: "general",
        image: TEST_IMAGE,
      });
    });
  });

  it("blocks submit until an image is selected", async () => {
    render(<App />);

    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "What is here?" } });

    const button = screen.getByRole("button", { name: /send question/i });
    expect(button).toBeDisabled();
    fireEvent.click(button);

    expect(askQuestion).not.toHaveBeenCalled();
    expect(screen.getByText(/upload an image to send with your question/i)).toBeInTheDocument();
  });

  it("shows API error responses inline", async () => {
    askQuestion.mockResolvedValue({ ok: false, error: "Backend error" });

    render(<App />);
    fireEvent.click(screen.getByRole("button", { name: /uploadermock/i }));
    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "What is here?" } });

    const button = screen.getByRole("button", { name: /send question/i });
    expect(button).not.toBeDisabled();
    fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByRole("alert")).toHaveTextContent("Backend error");
    });
  });

  it("renders backend mode hint when metadata is provided", async () => {
    askQuestion.mockResolvedValue({
      ok: true,
      data: {
        answer: "stubbed",
        model: "stub-model",
        latency_ms: 12,
        mode: "general",
        session_id: "session-1",
        backend_mode: "stub",
        fallback_reason: "remote_config_invalid",
        history: [
          { role: "user", content: "Question?" },
          { role: "assistant", content: "stubbed" },
        ],
      },
    });

    render(<App />);
    fireEvent.click(screen.getByRole("button", { name: /uploadermock/i }));
    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "Question?" } });
    const button = screen.getByRole("button", { name: /send question/i });
    fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByText(/answer generated by stub model/i)).toBeInTheDocument();
    });
  });

  it("keeps backend selection in the UI but ignores it in API requests", async () => {
    askQuestion.mockResolvedValue({
      ok: true,
      data: {
        answer: "ok",
        model: "stub-model",
        latency_ms: 10,
        mode: "general",
        session_id: "session-1",
        history: [
          { role: "user", content: "Question?" },
          { role: "assistant", content: "ok" },
        ],
      },
    });

    render(<App />);
    fireEvent.click(screen.getByRole("button", { name: /uploadermock/i }));
    const backendSelect = screen.getByLabelText(/backend/i);
    fireEvent.change(backendSelect, { target: { value: "stub" } });

    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "Question?" } });
    const button = screen.getByRole("button", { name: /send question/i });
    fireEvent.click(button);

    await waitFor(() => {
      expect(askQuestion).toHaveBeenCalled();
    });
    expect(askQuestion).toHaveBeenCalledWith({
      question: "Question?",
      mode: "general",
      image: TEST_IMAGE,
    });
  });
});
