import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { useEffect } from "react";
import { vi } from "vitest";
import App from "./App";

let autoSelectImage = false;

vi.mock("./components/ImageUploader", () => ({
  default: ({ onFileSelected }) => {
    useEffect(() => {
      if (autoSelectImage) {
        const file = new File(["123"], "test.png", { type: "image/png" });
        onFileSelected(file);
      }
      // Intentionally run once for test setup.
    }, []);
    return <div>UploaderMock</div>;
  },
}));

vi.mock("./api/client", () => ({
  askQuestion: vi.fn(),
}));

import { askQuestion } from "./api/client";

describe("App", () => {
  beforeEach(() => {
    autoSelectImage = false;
    vi.clearAllMocks();
  });

  it("disables send when no image is selected", () => {
    render(<App />);
    const button = screen.getByRole("button", { name: /send question/i });
    expect(button).toBeDisabled();
    fireEvent.click(button);
    expect(askQuestion).not.toHaveBeenCalled();
  });

  it("shows API error responses inline", async () => {
    autoSelectImage = true;
    const { askQuestion } = await import("./api/client");
    askQuestion.mockResolvedValue({ ok: false, error: "Backend error" });

    render(<App />);
    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "What is here?" } });

    const button = screen.getByRole("button", { name: /send question/i });
    expect(button).not.toBeDisabled();
    fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByRole("alert")).toHaveTextContent("Backend error");
    });
  });

  it("renders backend mode hint when metadata is provided", async () => {
    autoSelectImage = true;
    const { askQuestion } = await import("./api/client");
    askQuestion.mockResolvedValue({
      ok: true,
      data: {
        answer: "stubbed",
        model: "stub-model",
        latency_ms: 12,
        mode: "general",
        session_id: "session-1",
        backend_mode: "stub",
        fallback_reason: "remote_config_invalid",
        history: [
          { role: "user", content: "Question?" },
          { role: "assistant", content: "stubbed" },
        ],
      },
    });

    render(<App />);
    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "Question?" } });
    const button = screen.getByRole("button", { name: /send question/i });
    fireEvent.click(button);

    await waitFor(() => {
      expect(screen.getByText(/answer generated by stub model/i)).toBeInTheDocument();
    });
  });

  it("sends backend selection to the API", async () => {
    autoSelectImage = true;
    const { askQuestion } = await import("./api/client");
    askQuestion.mockResolvedValue({
      ok: true,
      data: {
        answer: "ok",
        model: "stub-model",
        latency_ms: 10,
        mode: "general",
        session_id: "session-1",
        history: [
          { role: "user", content: "Question?" },
          { role: "assistant", content: "ok" },
        ],
      },
    });

    render(<App />);
    const backendSelect = screen.getByLabelText(/backend/i);
    fireEvent.change(backendSelect, { target: { value: "stub" } });

    const input = screen.getByLabelText("Question input");
    fireEvent.change(input, { target: { value: "Question?" } });
    const button = screen.getByRole("button", { name: /send question/i });
    fireEvent.click(button);

    await waitFor(() => {
      expect(askQuestion).toHaveBeenCalled();
    });
    expect(askQuestion).toHaveBeenCalledWith(expect.objectContaining({ backend: "stub" }));
  });
});
